builders:
  vm_generator:
    import: 'package:vm_generator/vm_generator.dart'
    builder_factories: ['vmBuilderFactory']
    build_extensions: {'.dart': ['.g.dart']}
    auto_apply: root_package
    build_to: source
targets:
  $default:
    builders:
      vm_generator:
        generate_for:
          - lib/**/*_vm.dart